apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
namespace: default
images:
- name: backend
  newName: 862029645377.dkr.ecr.us-east-1.amazonaws.com/backend
  newTag: <IMAGE_TAG>
- name: frontend
  newName: 444917595510.dkr.ecr.us-east-1.amazonaws.com/backend
  newTag: tag1
